- name: Install Unattended Upgrades Packages
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Update Unattended Upgrades Configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
  - 10periodic
  - 50unattended-upgrades
